name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: nightly
          components: rust-docs

      - uses: jontze/action-mdbook@v2
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          use-mermaid: true

      - name: Check for broken links
        run: |
          curl -sSLo linkcheck.sh \
            https://raw.githubusercontent.com/rust-lang/rust/master/src/tools/linkchecker/linkcheck.sh
          # Cannot use --all here because of the generated redirect pages aren't available.
          sh linkcheck.sh book

      - name: Run vale checks
        run: |
          sudo snap install vale
          vale sync
          vale --no-wrap --minAlertLevel=suggestion src
          if [ $? -ne 0 ] || [ "$(vale --output=line --no-wrap --minAlertLevel=suggestion src | wc -l)" -ne 0 ]; then
            echo "Vale found issues. Please fix them before merging."
            exit 1
          fi

      - name: Deploy book
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force_orphan: true
          publish_dir: ./book
