name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: stable

      - name: Install Python dependencies
        run: |
          pip3 install --user python-dateutil linkchecker
      - name: Put pip binary directory into path
        run: echo "~/.local/bin" >> $GITHUB_PATH

      - name: Cache Cargo installed binaries
        uses: actions/cache@v3
        id: cache-cargo
        with:
          path: ~/cargo-bin
          key: cache-cargo
      - name: Install mdbook and mdbook-mermaid
        if: steps.cache-cargo.outputs.cache-hit != 'true'
        run: cargo install mdbook mdbook-mermaid
      - name: Copy mdbook and mdbook-mermaid to cache directory
        if: steps.cache-cargo.outputs.cache-hit != 'true'
        run: |
          mkdir ~/cargo-bin
          cp ~/.cargo/bin/mdbook ~/cargo-bin
          cp ~/.cargo/bin/mdbook-mermaid ~/cargo-bin
      - name: Put new cargo binary directory into path
        run: echo "~/cargo-bin" >> $GITHUB_PATH

      - name: Build book
        run: mdbook build
      - name: Test book
        run: mdbook test
      - name: Check links
        run: linkchecker book

      - name: Deploy book
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force_orphan: true
          publish_dir: ./book
